version: "3"
services:
  ui:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    restart: always
    image: ui-img
    container_name: ui
    volumes:
      - ./frontend:/code/frontend
      - ./.babelrc:/code/.babelrc
      - ./webpack.config.js:/code/webpack.config.js
      - ./package.json:/code/package.json
      - /code/node_modules
    depends_on:
      - mongo
  api:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    restart: always
    image: api-img
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/code/backend
      - ./package.json:/code/package.json
      - /code/node_modules
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/site.nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - api
      - ui